### ISSUE TITLE
Licence du projet

### ISSUE THREAD

**Issue by linogaliana** [Orlogskapten/dvf_ensae_sbra#3]
Ce n'est pas moi qui vous évalue mais je trouve votre travail très intéressant.

Je vous suggère de mettre en place une licence qui vous permette de conserver la paternité de votre propriété intellectuelle pour ne pas vous faire "voler" votre travail par un acteur peu scrupuleux

**Comment by Orlogskapten** [comment]
Bonjour monsieur,

Merci beaucoup on a oublié, on met ça en place de suite !
